### ISSUE TITLE
Preselection_faces.py Does not work in Blender 2.8

### ISSUE THREAD

**Issue by MightyBOBcnc** [bobtherobot/BetterBlender#3]
Title.  The addon cannot be activated due to code changes between 2.79 and 2.8.

Traceback (most recent call last):
  File "C:\Portable\blender-2.81a-windows64\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Portable\blender-2.81a-windows64\2.81\scripts\addons\preselection_faces.py", line 46, in <module>
    from bgl import (glColor4f, glEnable, glDisable, glBegin, glEnd,
ImportError: cannot import name 'glColor4f' from 'bgl' (unknown location)
